---
title: "How to calculate Cumulative portfolio returns in Python"
author: "DD"
date: "2018-04-10"
description: "Calculating cumulative portfolio returns in Python"
output: html_document
---

## Calculating Cumulative portfolio returns in Python

In the last post we learned how to construct a portfolio in python. We also learned how to calculate the daily portfolio returns. In this post we will learn how to calculate portfolio cumulative returns.

First lets load the library.

```{python}

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas_datareader as web
```


Then lets load the ticker symbols for our assets that we will include in our portfolio.

```{python}

#  Assets to be included in the portfolio

tickers = ['BND', 'VB', 'VEA', 'VOO', 'VWO']

```

We will also create a vector for our asset weights.

```{python}

# Asset weights

wts = [0.1,0.2,0.25,0.25,0.2]


```

Next lets download the price data from yahoo finance.

```{python}

price_data = web.get_data_yahoo(tickers,
                               start = '2013-01-01',
                               end = '2018-03-01')
                               
```


```{python}

price_data = price_data['Adj Close']

```


Next we will calculate the daily returns for our assets.

```{python}

ret_data = price_data.pct_change()[1:]

```


We will then calcualte the weighted average of our asset returns.

```{python}

weighted_returns = (wts * ret_data)
print(weighted_returns.head())

```


Finally the portfolio returns are the sum of the weighted returns.

```{python}

port_ret = weighted_returns.sum(axis=1)
# axis =1 tells pandas we want to add
# the rows

```


To calculate cumulative returns we need to use the `cumprod()` function.


```{python}

cumulative_ret = (port_ret + 1).cumprod()

```

Lastly we will plot our portfolios cumulative returns.

```{python}

fig = plt.figure()
ax1 = fig.add_axes([0.1,0.1,0.8,0.8])
ax1.plot(cumulative_ret)
ax1.set_xlabel('Date')
ax1.set_ylabel("Cumulative Returns")
ax1.set_title("Portfolio Cumulative Returns")
plt.show();

```


